### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by jayallen** [sjl/friendly-find#13]
Hi there. Nice work on ffind.  I use it all the time since I installed it.

I know you said you'd get around to it but I figured there should be a case for it (and some support): We love manpages!

I was wondering it, perchance, you could include one ASAP even if it just contains the information in the README because it's jarring to get an man error for a Homebrew-installed utility (since it's rare they don't have them). That's especially true of the ones I use quite often.

Thanks much for your work!

**Comment by sjl** [comment]
I added one from `help2man`.
